### ISSUE TITLE
package names in groovy-devel branch don't match those in moveit-ros

### ISSUE THREAD

**Issue by jonbinney** [moveit/moveit_pr2#1]
For example, in pr2_moveit_apps, move_group.launch tries to launch the move group node with "pkg="move_group"". But that is now part of one big moveit_ros_planning package.

**Comment by isucan** [comment]
The two packages in moveit_pr2 are defined manually for fuerte. Since we defined those, we have implemented the Setup Assistant, which generates the package we should be using. I plan to release a pre-generated package as part of moveit_pr2, but the packages in there now (pr2_moveit_config &  pr2_moveit_apps) are not going to be in Groovy.
